experiment_type: TrainMLP
trainer_config:
    trainer_type: Trainer
    mlp_config:
        input_dim: 9
        output_dim: 1
        hidden_dims:
        - 256
        - 256
        start_activation: false
        end_activation: false
    optimizer_config:
        lr: 0.02
        weight_decay: 0.0
    cube_distribution_config:
        distribution_type: CubeDistribution
        input_dim: 9
        indices_list:
        - [0, 1]
        - [2, 3]
        - [4, 5]
        - [6, 7]
        - [0, 3]
        - [3, 4]
        weights:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        normalize: true
        noise_mean: 0.0
        noise_std: 0.0
    train_size: 256
    test_size: 256
    batch_size: 64
    epochs: 2000
    use_full_batch: false
    weight_decay_l1: 0.01
home_directory: experiment_runs/new_testing/1
seed: 12321245
edge_thresholds:
- 0.01
