experiment_type: TrainMLP
trainer_config:
    trainer_type: Trainer
    mlp_config:
        input_dim: 16
        output_dim: 1
        hidden_dims:
        - 128
        - 128
        activation: relu
        start_activation: false
        end_activation: false
        bias: true
    optimizer_config:
        lr: 0.005
        weight_decay: 0.0
    cube_distribution_config:
        distribution_type: CubeDistribution
        input_dim: 16
        indices_list:
        - [0]
        - [0, 1]
        - [0, 1, 2]
        weights:
        - 1.0
        - 1.0
        - 1.0
        normalize: true
        noise_mean: 0.0
        noise_std: 0.1
    train_size: 1024
    test_size: 1024
    batch_size: 128
    epochs: 3
    use_full_batch: false
    weight_decay_l1: 0.0004
home_directory: experiment_runs/test/39
seed: 12321245
run_parallel: false
