experiment_type: Cube
dimension: 20
k: 2
depth: 3
width: 10
learning_rate: 0.009
weight_decay: 0.0
weight_decay_l1: 1.0
mup: true
epochs: 2000
early_stopping: 0.00001
train_size: 2048
batch_size: 64
home_directory: experiment_runs/real_cube_mup_skinny/l1dec_1/depth_deep_3
seed: 12345115
run_parallel: false